title: "La dilettante"

À propos: "Blog voyage sans ligne éditoriale."
markdown: kramdown
disqus_short_name: disqus-demo-page

plugins:
  - jekyll-paginate
  - jemoji

paginate_path: "/page:num/"

paginate: 5

main_toc:
  - title: Accueil
    url: ""
  - title: À propos
    url: "apropos"
  - title: Auteur
    url: "auteur"

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
